matrix:
  include:
    - language: ruby
      rvm:
      - 2.7.7

      before_script:
        - chmod +x ./script/cibuild

      script: ./script/cibuild

      env:
        global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

      sudo: false
      exclude: [vendor]

    - language: python
      python: 3.5
      install: pip3 install -r ./script/pyscripts/requirements.txt
      script: ./script/pytests
