name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install bundler
      run: gem install bundler
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bash ./cibuild

